### PR TITLE
This upgrades Ext JS to Version 6.2.0

### PR DESCRIPTION
**Pull request by KaiVolland**

### CODE REVIEW

**Comment by annarieger** [comment]
+1 from me, thx for upgrading :pineapple:

**Comment by marcjansen** [comment]
I hear toasts have a different default alignment now... nonetheless,  we can adjust that later, if needed at all. Please merge and thanks.

**Comment by marcjansen** [comment]
... also please fix the build.

**Comment by KaiVolland** [comment]
I skipped the tests!
I think that mochajs/phantomjs is maybe not a suitable testenvironment for extjs applications. I'll test alternatives in the next hours.

**Comment by marcjansen** [comment]
good for me,  skipping is 🖒

**Pull request merged**
